### ISSUE TITLE
[Question] losing precisions in hdf5 image after conversion from fits

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/hdf5converters#9]
@veggiesaurus @confluence I remember at some stage we talked about this issue. Just wondering if this issue remains. 

with 

> SCHEMA_VERSION = 0.2
HDF5_CONVERTER = hdf_convert
HDF5_CONVERTER_VERSION = 0.1.8

we see 
![Screen Shot 2020-04-14 at 5 15 04 PM](https://user-images.githubusercontent.com/20819712/79207661-91c27300-7e73-11ea-8a51-8c0fff1eb347.png)

Its fits image is
![Screen Shot 2020-04-14 at 5 15 33 PM](https://user-images.githubusercontent.com/20819712/79207703-9dae3500-7e73-11ea-9a87-bbb2595570a4.png)

We can see floating numbers are truncated (e.g. BMAJ, BMIN, BPA). Due to this, the world coordinate derived from CRVAL1 and CRVAL2 has an offset compared to fits.

**Comment by confluence** [comment]
This is the repository for the Python converter, which is no longer being maintained. This issue should be reopened in [the C++ converter repository](https://github.com/idia-astro/cpp_hdf5converter).

We recently fixed a precision issue in that converter, so please test with the latest development version to see if this issue still occurs.
